[general]
listen_addr = "0.0.0.0:8000"

[paths]
# Proxying to your app's server
"/mono" = "http://localhost:8080"


# Proxying to a remote server works too
"/static" = "https://cdn.site.org"

[oauth]
tokeninfo_url =  "token url"

[oauth.policies.default]
enabled = false

[oauth.policies.mono]
url = "/mono/*"

[oauth.policies.mono.realms.EMPLOYEES]
uids = [""]
scopes= [""]

[oauth.policies.mono.realms.SERVICES]
uids = [""]
scopes = [""]

