[general]
listen_addr = "0.0.0.0:8000"

[paths]
# Proxying to your app's server
"/mono" = "http://localhost:8080"

# Proxying to a remote server works too
"/static" = "https://cdn.site.org"

[oauth]
tokeninfo_url =  "token url"
[realms]
    [realms.EMPLOYEES]
        uids = ["ssarabadani"]
    [realms.SERVICES]
        scopes = ["read.all"]
        uids = [""]

